name: Deploy to Server

on:
  push:
    branches:
      - main  # Set this to the branch you want to deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Use the node version that matches your Meteor app requirements

    - name: Install Dependencies
      run: |
        curl https://install.meteor.com/ | sh
        meteor npm install

    - name: Build App
      run: |
        meteor build --directory /tmp/build

    - name: Deploy to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.PRIVATE_SSHKEY }}
        port: 22
        source: "."
        target: "taskgoblin"
